name: Build and Commit Hugo Site

env:
  WC_HUGO_VERSION: '0.126.3'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: write  # This needs to be 'write' to push changes to the repo

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build website
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.WC_HUGO_VERSION }}
        extended: true

    - name: Cache Hugo modules
      uses: actions/cache@v3
      with:
        path: /tmp/hugo_cache_runner/
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-
    
    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
      run: |
        echo "Building the site..."
        hugo --minify

    - name: Move compiled site to 'compiled-site' folder
      run: |
        mkdir -p compiled-site
        mv public/* compiled-site/

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit compiled files
      run: |
        git add compiled-site/*
        git commit -m "Compiled site at $(date +'%Y-%m-%d %H:%M:%S')"
    
    - name: Push changes to the repository
      run: git push
